server:
  port: 8383
spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: root
#    url: jdbc:mariadb://localhost:3306/credentialdb
#    username: root
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  application:
       name: login-service 
  mail:
    host: smtp.gmail.com
    username: mmb.notify.mail@gmail.com
    password: afruhcuawwhpwbbb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true      
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
  client: 
      register-with-eureka: true
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
          
logging:
    file:
      name: login-log.log
      
management:
  endpoints:
    web:
      exposure:
        include: "*" 